version: "3.7"
services:
  cc-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - cc-database:/var/lib/postgresql/data
      #   .sh, .sql, .sql.gz files in /docker-entrypoint-initdb.d will be
      # executed when the (database) container is started for the first time
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: codechallenge
    restart: always
  cc-server:
    image: cc-nodejs-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - cc-db
volumes:
  cc-database:
