CREATE TABLE Customer (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  country VARCHAR(2) NOT NULL,
  zip VARCHAR(10) NOT NULL
);

CREATE TABLE Item (
  id INTEGER PRIMARY KEY,
  price DECIMAL NOT NULL
);
