CREATE TABLE Customer (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  country VARCHAR(2) NOT NULL,
  zip VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Item (
  id INT NOT NULL AUTO_INCREMENT,
  price INT NOT NULL,
  PRIMARY KEY (id)
);
